apache:
    image: httpd:latest
    expose:
    - 80
    volumes:
    - ./website:/usr/local/apache2/htdocs
nginx:
    image: nginx
    expose:
        - 80
    volumes:
    - ./website:/usr/share/nginx/html
haproxy:
    image: haproxy
    volumes:
        - ./haproxy_config:/usr/local/etc/haproxy/
    links:
        - apache
        - nginx
    ports:
        - "8080:80"  
    expose:
        - 80  
node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
haproxy-exporter:
    image: quay.io/prometheus/haproxy-exporter
    links: 
        - haproxy
    ports:
        - "9101:9101"
    command: --haproxy.scrape-uri="http://admin:chaF_ai!-0quim@haproxy:80/status;csv" 
prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
    - "9090:9090"
    links: 
        - haproxy-exporter
        - node-exporter
grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    links:
      - prometheus
    volumes:
      - ./grafana_config/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      - ./grafana_config/plugins:/var/lib/grafana/plugins
